permalink: ":year/:title.html"
#auto: true
exclude:
  - deploy.sh

# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Karsten Jeschkies"
description: > # this means to ignore newlines until "email:"
   Just a Page About Stuff I Do

#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Karsten Jeschkies'
author: 'Karsten Jeschkies'
author_image: "/assets/images/author.jpg"


url: "http://www.blackmagiclabs.com/portfolio"
baseurl: ""
