# Permalinks
permalink:           pretty

# Setup
title:               Karsten Jeschkies
tagline:             'Just a Page About Stuff I Do'
description:         "I'm a software engineer from Germany who likes to solve complicated problems with simple solutions."
url:                 'http://nosy.one'
baseurl:             '/portfolio'

# About/contact
author:
  name:              Karsten Jeschkies
  url:               https://nosy.one
  email:             ''

# Custom vars
version:             1.0.0
markdown:            kramdown
