# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Karsten Jeschkies
tagline:             'Just a Page About Stuff I Do'
description:         "I'm a software engineer from Germany who likes to solve complicated problems with simple solutions."
url:                 'http://blackmagiclabs.com/blog'
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Karsten Jeschkies
  url:               https://www.blackmagiclabs.com
  email:             ''

# Custom vars
version:             1.0.0
